# Generated by Django 5.2.4 on 2025-08-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingparticipant',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
